import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.165.0/build/three.module.js';

const $ = id => document.getElementById(id);
const engines = [...document.querySelectorAll('.engine-card')];
const scenes = [
  ['Normal traffic baseline','1,284','safe','Baseline is stable','Continuous metadata is entering the enclave. No payload data is opened.','100%'],
  ['DDoS injection · Slowloris','18,920','danger','Network flood pattern detected','The attack simulator has generated a sharp burst of slow connection exhaustion attempts.','93%'],
  ['C2 beacon replay','1,401','warning','Regular external check-in observed','A repeating timing signature points to a possible hidden remote-control channel.','86%'],
  ['DNS tunnel replay','1,562','warning','Encoded DNS pattern identified','Long, random-looking DNS labels deviate from the learned service baseline.','89%'],
  ['Evidence packet compiled','1,327','safe','Findings prepared for human review','The isolated enclave has produced an explainable intelligence record—without acting on the protected network.','100%']
];
let activeScene=0, started=false;
const wait = ms => new Promise(resolve=>setTimeout(resolve,ms));
function line(text){$('bootLog').textContent=`› ${text}`}
async function launch(){
  if(started)return; started=true; const button=$('launchButton');button.disabled=true;button.textContent='Initializing engines…';
  const actions=[['Loading TRex baseline profiles…','Generating safe DNS, TLS and web flow metadata','ONLINE'],['Loading Slowloris simulation recipe…','Attack injection held until directed by scenario','ARMED'],['Mounting isolated sandbox timing feed…','C2 analyser ready; encrypted content stays sealed','ONLINE']];
  for(let i=0;i<3;i++){const card=engines[i];card.classList.add('starting');card.querySelector('.engine-state span').textContent='STARTING';line(actions[i][0]);await wait(1500);line(actions[i][1]);await wait(1700);card.classList.remove('starting');card.classList.add('ready');card.querySelector('.engine-state span').textContent=actions[i][2]}
  line('All engines synchronized. Opening one-way data fabric…');await wait(1200);$('bootView').classList.add('exit');$('liveLab').classList.add('live');$('simulationState').classList.add('running');$('simulationState').innerHTML='<i></i> LIVE · ONE-WAY TELEMETRY ACTIVE';initThree();
}
function setScene(index){activeScene=index;const [name,rate,type,title,text,confidence]=scenes[index];$('sceneName').textContent=name;$('flowRate').textContent=rate;$('alertConfidence').textContent=confidence;const alert=$('liveAlert');alert.className=`live-alert ${type}`;alert.querySelector('small').textContent=type==='safe'?'OBSERVATION':'ACTIVE DETECTION';alert.querySelector('h3').textContent=title;alert.querySelector('p').textContent=text;alert.querySelector('.alert-mark').textContent=type==='safe'?'✓':'!';document.querySelectorAll('.scene-step').forEach((b,i)=>b.classList.toggle('active',i===index))}
document.querySelectorAll('.scene-step').forEach(b=>b.addEventListener('click',()=>setScene(+b.dataset.scene)));
$('launchButton').addEventListener('click',launch);$('startButton').addEventListener('click',()=>{document.querySelector('#scenarios').scrollIntoView({behavior:'smooth',block:'start'});setTimeout(launch,550)});$('restartButton').addEventListener('click',()=>location.reload());

function initThree(){
  const canvas=$('networkCanvas'), scene=new THREE.Scene(), camera=new THREE.PerspectiveCamera(42,1,.1,100), renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true});camera.position.set(0,1.2,12);renderer.setPixelRatio(Math.min(devicePixelRatio,2));scene.add(new THREE.AmbientLight(0xffffff,2));const light=new THREE.DirectionalLight(0xfff0d0,2.3);light.position.set(2,5,5);scene.add(light);
  const floor=new THREE.Mesh(new THREE.PlaneGeometry(22,10),new THREE.MeshBasicMaterial({color:0xf4f7ee,transparent:true,opacity:.85}));floor.rotation.x=-Math.PI/2;floor.position.y=-2.05;scene.add(floor);const grid=new THREE.GridHelper(20,28,0xa8c2a9,0xd9e5d8);grid.position.y=-2;grid.material.transparent=true;grid.material.opacity=.5;scene.add(grid);
  const node=(x,color)=>{const g=new THREE.Group(),core=new THREE.Mesh(new THREE.IcosahedronGeometry(.43,2),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.24})),ring=new THREE.Mesh(new THREE.TorusGeometry(.7,.023,8,40),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.7}));ring.rotation.x=Math.PI/2;g.add(core,ring);g.position.set(x,0,0);scene.add(g);return{g,core,ring}};const nodes=[node(-5,0x7b57b7),node(0,0xd49a36),node(5,0x6a3f87)];const mat=new THREE.LineBasicMaterial({color:0x9a72b3,transparent:true,opacity:.5});[[-4.5,-.45],[.45,4.5]].forEach(([a,b])=>scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(a,0,0),new THREE.Vector3(b,0,0)]),mat)));
  const packets=[],normalMat=new THREE.MeshBasicMaterial({color:0x7c62d0}),threatMat=new THREE.MeshBasicMaterial({color:0xdf6258}),geo=new THREE.SphereGeometry(.07,8,8);for(let i=0;i<56;i++){const mesh=new THREE.Mesh(geo,normalMat);scene.add(mesh);packets.push({mesh,p:Math.random()*9,s:.014+Math.random()*.014})}const threats=[];for(let i=0;i<24;i++){const mesh=new THREE.Mesh(new THREE.SphereGeometry(.05,7,7),threatMat);mesh.visible=false;scene.add(mesh);threats.push(mesh)}
  const resize=()=>{const r=canvas.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()};new ResizeObserver(resize).observe(canvas);resize();let t=0;const loop=()=>{requestAnimationFrame(loop);t+=.016;camera.position.x=Math.sin(t*.17)*.18;camera.lookAt(0,0,0);nodes.forEach((n,i)=>{n.ring.rotation.z=t*(i%2?-.4:.4);n.core.scale.setScalar(1+Math.sin(t*2+i)*.055)});packets.forEach((p,i)=>{p.p+=p.s*(activeScene===1?3:1);p.mesh.position.set(-4.45+p.p%9,Math.sin((p.p+i)*2)*.16,.12)});const attack=activeScene>0&&activeScene<4;threats.forEach((m,i)=>{m.visible=attack;if(attack){const a=i/threats.length*Math.PI*2+t*(activeScene===1?1.4:.3),r=activeScene===1?3.6:2.7;m.position.set(-1.4+Math.cos(a)*r,Math.sin(a)*r*.75,.24);if(activeScene===2)m.position.set(-3+(t%2)*6,Math.sin(i)*.22,.24);if(activeScene===3)m.position.set(-2+(i%7)*.58,.85+Math.sin(t+i)*.13,.24)}});renderer.render(scene,camera)};loop();setScene(0);setInterval(()=>{if(activeScene<4)setScene(activeScene+1)},12000)}
